"""add project collector fields

Revision ID: eb9ae91657c9
Revises: 5245f2e3babc
Create Date: 2026-02-15 18:23:56.707965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb9ae91657c9"
down_revision: Union[str, None] = "5245f2e3babc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("search_engine", sa.String(length=10), nullable=False, server_default="both"))
    op.add_column("projects", sa.Column("region_google", sa.String(length=200), nullable=True))
    op.add_column("projects", sa.Column("region_yandex", sa.Integer(), nullable=False, server_default="213"))
    op.add_column("projects", sa.Column("ywm_host_id", sa.String(length=200), nullable=True))
    op.add_column("projects", sa.Column("gsc_site_url", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "gsc_site_url")
    op.drop_column("projects", "ywm_host_id")
    op.drop_column("projects", "region_yandex")
    op.drop_column("projects", "region_google")
    op.drop_column("projects", "search_engine")
    # ### end Alembic commands ###
